/*
 * EditCodeTemplate.java
 * Created on October 23, 2007, 11:34 AM
 *
 * Copyright (C) 2008 Mrityunjoy Saha
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package org.apex.base.settings.ui;

import org.apex.base.settings.CodeTemplatesConfiguration;
import org.apex.base.settings.InvalidSettingsParameterException;
import org.apex.base.settings.SettingsMessageManager;
import javax.swing.JTable;

/**
 * A form to edit code templates. Abbreviation can not be changed by user.
 * @author Mrityunjoy Saha
 * @version 1.0
 * @since Apex 1.0
 */
public class EditCodeTemplate extends CodeTemplateChangeSupport {

    /**
     * Creates new form {@code EditCodeTemplate} using specified code templates
     * configuration, a table which displays all code templates, selected
     * abbreviation and selected code template..
     * @param codeTemplatesConfiguration Code templates configuration.
     * @param codeTemplates A table where code templates are displayed.
     * @param selectedAbbreviation Selected abbreviation.
     * @param selectedTemplate Selected code template.
     */
    public EditCodeTemplate(
            CodeTemplatesConfiguration codeTemplatesConfiguration,
            JTable codeTemplates, String selectedAbbreviation,
            String selectedTemplate) {
        super(codeTemplatesConfiguration, codeTemplates,
                selectedAbbreviation, selectedTemplate);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane11 = new javax.swing.JScrollPane();
        template = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        abbreviation = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        ok = new javax.swing.JButton();

        template.setColumns(20);
        template.setRows(5);
        template.setText(getSelectedTemplate());
        jScrollPane11.setViewportView(template);

        jLabel1.setText("Abbreviation:");

        abbreviation.setText(getSelectedAbbreviation());

        jLabel3.setText("Template:");

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        ok.setText("Ok");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancel)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(abbreviation, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(420, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(abbreviation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancel)
                    .addComponent(ok))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        try {
            // Get entered template
            String enteredTemplate = this.template.getText();
            validateTemplate(enteredTemplate);
            // Update the template
            this.codeTemplatesConfiguration.getCodeTemplates().
                    put(getSelectedAbbreviation(), enteredTemplate);
            // Update the view
            this.codeTemplates.getModel().
                    setValueAt(getSelectedAbbreviation(),
                    this.codeTemplates.getSelectedRow(), 0);
            this.codeTemplates.getModel().
                    setValueAt(enteredTemplate,
                    this.codeTemplates.getSelectedRow(), 1);
            int editedRowNum = this.codeTemplates.getSelectedRow();
            this.codeTemplates.clearSelection();
            if (this.codeTemplates.getRowCount() > 0 &&
                    this.codeTemplates.getRowSelectionAllowed()) {
                this.codeTemplates.setRowSelectionInterval(editedRowNum,
                        editedRowNum);
            }
            closeWindow();
        } catch (InvalidSettingsParameterException ex) {
            SettingsMessageManager.showErrorMessage(this, ex.getErrorCode(),
                    ex.getPlaceHolders());
            this.template.requestFocus();
        }
}//GEN-LAST:event_okActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        closeWindow();
}//GEN-LAST:event_cancelActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abbreviation;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JButton ok;
    private javax.swing.JTextArea template;
    // End of variables declaration//GEN-END:variables
}
