/*
 * AboutToolView.java
 * Created on 2 November, 2007, 3:29 AM
 *
 * Copyright (C) 2008 Mrityunjoy Saha
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package org.apex.base.help.ui;

import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import javax.swing.Icon;
import org.apex.base.core.EditorBase;
import org.apex.base.data.EditorContext;
import org.apex.base.ui.text.UIDialogModel;
import javax.swing.JDialog;
import org.apex.base.constant.EditorKeyConstants;
import org.apex.base.constant.MenuConstants;
import org.apex.base.core.MenuManager;
import org.apex.base.logging.Logger;
import org.apex.base.menu.ViewDocumentInBrowserMenu;
import org.apex.base.util.ImageCreator;

/**
 * A panel to display information about the application.
 * @author Mrityunjoy Saha
 * @version 1.0
 * @since Apex 1.0
 */
public class AboutToolView extends javax.swing.JPanel implements UIDialogModel {

    /**
     * The dialog window containing this panel.
     */
    private JDialog containerWindow;
    /**
     * Online support URI.
     */
    private static URI onlineSupportURI;

    /**
     * Creates a new instance of {@code AboutToolView}.
     * It initializes all components in the panel.
     */
    public AboutToolView() {
        initComponents();
        try {
            onlineSupportURI = new URL(getContext().getEditorProperties().
                    getEditorSupportUrl()).toURI();
        } catch (MalformedURLException ex) {
            Logger.logError(
                    "Could not form online support URI:MalformedURLException",
                    ex);
        } catch (URISyntaxException use) {
            Logger.logError(
                    "Could not form online support URI:URISyntaxException",
                    use);
        }
    }

    /**
     * Returns application logo icon.
     * @return The application logo icon.
     */
    private Icon getApplicationShortLogo() {
        return ImageCreator.createImageIcon(
                EditorKeyConstants.APPLICATION_SHORT_LOGO);
    }

    /**
     * Returns the copyright info.
     * @return The copyright info.
     */
    private String getCopyrightInfo() {
        return "<html><p align=\"center\">Copyright (c) 2008-2013 Mrityunjoy Saha<br />www.openapex.org</p>";
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ok = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        version = new javax.swing.JLabel();
        info = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        copyrightInfo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        ok.setText("Ok");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        jLabel3.setText("Version:");

        version.setText(getVersion());

        info.setText(getInfo());

        contact.setText(getContactInfo());
        contact.setToolTipText(getContext().getEditorProperties().getEditorSupportUrl());
        contact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactMouseClicked(evt);
            }
        });

        logo.setIcon(getApplicationShortLogo());

        copyrightInfo.setText(getCopyrightInfo());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(version)
                            .addContainerGap(298, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                                .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(info, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(contact, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(copyrightInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(114, 114, 114))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(version)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyrightInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contact)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ok)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        getContainerWindow().setVisible(false);
}//GEN-LAST:event_okActionPerformed

    private void contactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactMouseClicked
        ((ViewDocumentInBrowserMenu) MenuManager.getMenuById(
                MenuConstants.VIEW_IN_WEB_BROWSER)).browse(onlineSupportURI);
    }//GEN-LAST:event_contactMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contact;
    private javax.swing.JLabel copyrightInfo;
    private javax.swing.JLabel info;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logo;
    private javax.swing.JButton ok;
    private javax.swing.JLabel version;
    // End of variables declaration//GEN-END:variables

    public void setContainerWindow(JDialog window) {
        this.containerWindow = window;
    }

    public JDialog getContainerWindow() {
        return this.containerWindow;
    }

    public EditorContext getContext() {
        return EditorBase.getContext();
    }

    /**
     * Returns the version of application.
     * @return The version of application.
     */
    private String getVersion() {
        return getContext().getEditorProperties().getEditorVersion();
    }

    /**
     * Returns a brief description of the application.
     * @return A brief description of the application.
     */
    private String getInfo() {
        return "<html>This is a general purpose editor which can be used to edit text "
                + "files. It supports synatx highlighting for Java, C, C++, Perl, SQL, JSP, HTML etc., tooling for Java. Many UI features are configurable.";
    }

    /**
     * Returns the contact information.
     * @return The contact information.
     */
    private String getContactInfo() {
        return "<html><p align=\"center\">To know more about the edtior or to contribute to development, please visit: <a href=\"" + getContext().
                getEditorProperties().getEditorSupportUrl() + "\">" + getContext().
                getEditorProperties().getEditorSupportUrl() + "</a></p>";
    }
}
