/*
 * HelpMenuPage.java
 * Created on 4 November, 2007, 3:49 AM
 *
 * Copyright (C) 2008 Mrityunjoy Saha
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package org.apex.base.help.ui;

import org.apex.base.data.TreeModel;
import org.apex.base.help.HelpDataPane;
import org.apex.base.help.HelpTopic;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import javax.swing.tree.TreeSelectionModel;

/**
 * Sidebar links in help window.
 * @author Mrityunjoy Saha
 * @version 1.0
 * @since Apex 1.0
 */
public class HelpMenuPage extends javax.swing.JPanel {

    /**
     * The root help topic.
     */
    private HelpTopic helpTopic;
    /**
     * The current help topic.
     */
    private HelpTopic currentTopic;
    /**
     * The panel where help pages are displayed.
     */
    private HelpDataPane dataPane;

    /** 
     * Creates new form {@code HelpMenuPage} using specified root
     * help topic and a panel where help pages are displayed.
     * @param helpTopic The root help topic.
     * @param dataPane The panel where to display help pages.
     */
    public HelpMenuPage(HelpTopic helpTopic, HelpDataPane dataPane) {
        this.helpTopic = helpTopic;
        this.dataPane = dataPane;
        initComponents();
        content.getSelectionModel().setSelectionMode(
                TreeSelectionModel.SINGLE_TREE_SELECTION);
        // By default select the root menu
        this.content.setSelectionRow(0);
    }

    /**
     * Returns the tree model for help menus.
     * @return A tree data model.
     */
    private TreeModel getHelpMenuModel() {
        return new TreeModel(this.helpTopic);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        content = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        find = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        result = new javax.swing.JList();

        jTabbedPane1.setFocusable(false);

        content.setModel(getHelpMenuModel());
        content.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                contentValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(content);

        jTabbedPane1.addTab("Contents", jScrollPane1);

        jLabel1.setText("Find:");

        result.setModel(getHelpSearchResultModel());
        jScrollPane2.setViewportView(result);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(find, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(find, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Search", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

private void contentValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_contentValueChanged
    HelpTopic selectedHelpTopic = (HelpTopic) this.content.getSelectionPath().
            getLastPathComponent();
    this.currentTopic = selectedHelpTopic;
    if (!selectedHelpTopic.isLeaf()) {
        return;
    }
    // Open the target page
    this.dataPane.setPage(selectedHelpTopic.getTargetPageURL());

}//GEN-LAST:event_contentValueChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree content;
    private javax.swing.JTextField find;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList result;
    // End of variables declaration//GEN-END:variables

    /**
     * Returns the list model for search results.
     * @return A list data model.
     */
    private ListModel getHelpSearchResultModel() {
        return new DefaultListModel();
    }
}