/*
 * FindPanel.java
 * Created on December 30, 2010, 7:08 PM
 *
 * Copyright (C) 2010 Mrityunjoy Saha
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package org.apex.base.search.ui;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import org.apex.base.constant.MenuConstants;
import org.apex.base.core.EditorBase;
import org.apex.base.core.MenuManager;
import org.apex.base.data.EditorContext;
import org.apex.base.data.InputParams;
import org.apex.base.data.OutputParams;
import org.apex.base.event.FolderBrowserEventHandler;
import org.apex.base.event.FolderSearchEventHandler;
import org.apex.base.search.SearchTextModel;
import org.apex.base.ui.text.UIDialogModel;
import org.apex.base.util.DocumentData;

/**
 * A folder search form. User can change search preferences in this from and search for
 * text in selected folder with file and folder filters.
 * @author Mrityunjoy Saha
 * @version 1.0
 * @since Apex 1.3
 */
public class FolderSearchView extends javax.swing.JPanel implements UIDialogModel {

    /**
     * A find text event handler.
     */
    private FolderSearchEventHandler findEvent;
    /**
     * The search data model.
     */
    private SearchTextModel model;

    /**
     * Creates a new instance of {@code FindPanel} using specified search data model.
     * @param model The search data model.
     */
    public FolderSearchView(SearchTextModel model) {
        this.model = model;
        findEvent = new FolderSearchEventHandler();
        initComponents();
        this.folderBrowse.addActionListener(new FolderBrowserEventHandler(
                this.folder));
        // @TODO Help button is temporarily invisible - remove following line in later version.
        this.help.setVisible(false);
        this.searchKey.getEditor().getEditorComponent().addKeyListener(
                new SearchTextKeyListener());
        applyModel();
    }

    public void setContainerWindow(JDialog window) {
        this.containerWindow = window;
        applyModel();
        if (!DocumentData.isSelectedTextMultiLine(getContext())) {
            String selectedText = getContext().getEditorProperties().
                    getCurrentDocument().getEditor().
                    getSelectedText();
            this.searchKey.getEditor().setItem(selectedText);
            this.model.setSearchKey(selectedText);
        }
        selectSearchText();
    }

    public JDialog getContainerWindow() {
        return this.containerWindow;
    }

    /**
     * Selects the text in 'Search Text' field.
     */
    private void selectSearchText() {
        if (this.searchKey.getEditor().getItem() != null) {
            this.searchKey.getEditor().selectAll();
        }
    }

    /**
     * Applies the search data model to this form.
     */
    private void applyModel() {
        this.searchKey.setSelectedItem(this.model.getSearchKey());
        this.caseSensitive.setSelected(this.model.isCaseSensitive());
        this.wholeWord.setSelected(this.model.isWholeWord());
        this.highlightSearch.setSelected(this.model.isHighlightSearch());
        selectSearchText();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        searchKey = new javax.swing.JComboBox();
        caseSensitive = new javax.swing.JCheckBox();
        wholeWord = new javax.swing.JCheckBox();
        highlightSearch = new javax.swing.JCheckBox();
        find = new javax.swing.JButton();
        close = new javax.swing.JButton();
        help = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        folderBrowse = new javax.swing.JButton();
        folder = new javax.swing.JComboBox();
        fileFilter = new javax.swing.JComboBox();
        folderFilter = new javax.swing.JComboBox();
        includeSubfolders = new javax.swing.JCheckBox();
        allMatchingLines = new javax.swing.JCheckBox();
        allMatchingFiles = new javax.swing.JCheckBox();

        jCheckBox1.setText("jCheckBox1");

        jLabel1.setText("Find What:");

        searchKey.setEditable(true);
        searchKey.setModel(getSearchKeyListModel());
        searchKey.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                searchKeyItemStateChanged(evt);
            }
        });

        caseSensitive.setText("Match Case");
        caseSensitive.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        caseSensitive.setMargin(new java.awt.Insets(0, 0, 0, 0));
        caseSensitive.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                caseSensitiveItemStateChanged(evt);
            }
        });

        wholeWord.setText("Whole Words");
        wholeWord.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        wholeWord.setMargin(new java.awt.Insets(0, 0, 0, 0));
        wholeWord.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                wholeWordItemStateChanged(evt);
            }
        });
        wholeWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wholeWordActionPerformed(evt);
            }
        });

        highlightSearch.setText("Highlight Search");
        highlightSearch.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        highlightSearch.setMargin(new java.awt.Insets(0, 0, 0, 0));
        highlightSearch.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                highlightSearchItemStateChanged(evt);
            }
        });

        find.setText("Find");
        find.setFocusable(false);
        find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findHandler(evt);
            }
        });

        close.setText("Close");
        close.setFocusable(false);
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeHandler(evt);
            }
        });

        help.setText("Help");
        help.setFocusable(false);
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpHandler(evt);
            }
        });

        jLabel2.setText("Folder:");

        jLabel3.setText("File Filter:");

        jLabel4.setText("Folder Filter:");

        folderBrowse.setText("Browse");

        folder.setEditable(true);
        folder.setModel(getFolderListModel());

        fileFilter.setEditable(true);
        fileFilter.setModel(getFileFilterListModel());

        folderFilter.setEditable(true);
        folderFilter.setModel(getFolderFilterListModel());

        includeSubfolders.setText("Include Subfolders");
        includeSubfolders.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        includeSubfolders.setMargin(new java.awt.Insets(0, 0, 0, 0));
        includeSubfolders.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                includeSubfoldersItemStateChanged(evt);
            }
        });

        allMatchingLines.setText("All Matching Lines");
        allMatchingLines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allMatchingLinesActionPerformed(evt);
            }
        });

        allMatchingFiles.setText("All Matching Files");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allMatchingLines)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(folder, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fileFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(folderFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(help)
                            .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 67, Short.MAX_VALUE)
                            .addComponent(folderBrowse, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(find, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caseSensitive)
                            .addComponent(wholeWord))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(highlightSearch)
                            .addComponent(includeSubfolders)
                            .addComponent(allMatchingFiles))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {close, find, folderBrowse, help});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(find))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(folderBrowse)
                    .addComponent(folder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(close)
                    .addComponent(fileFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(folderFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(help))))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caseSensitive)
                    .addComponent(includeSubfolders))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wholeWord)
                    .addComponent(highlightSearch))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allMatchingLines)
                    .addComponent(allMatchingFiles))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void searchKeyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_searchKeyItemStateChanged
        this.model.setSearchKey((String) this.searchKey.getSelectedItem());
    }//GEN-LAST:event_searchKeyItemStateChanged

    private void caseSensitiveItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_caseSensitiveItemStateChanged
        this.model.setCaseSensitive(caseSensitive.isSelected());
    }//GEN-LAST:event_caseSensitiveItemStateChanged

    private void wholeWordItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_wholeWordItemStateChanged
        this.model.setWholeWord(wholeWord.isSelected());
    }//GEN-LAST:event_wholeWordItemStateChanged

    private void highlightSearchItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_highlightSearchItemStateChanged
        this.model.setHighlightSearch(highlightSearch.isSelected());
    }//GEN-LAST:event_highlightSearchItemStateChanged

    private void findHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findHandler
        findEvent.execute(model);
    }//GEN-LAST:event_findHandler

    private void closeHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeHandler
        getContainerWindow().setVisible(false);
    }//GEN-LAST:event_closeHandler

    private void helpHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpHandler
        // Find Help button pressed, linking to main help window.
        MenuManager.getMenuById(MenuConstants.HELP).processMenu(
                new InputParams(),
                new OutputParams());
}//GEN-LAST:event_helpHandler

    private void wholeWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wholeWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wholeWordActionPerformed

    private void includeSubfoldersItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_includeSubfoldersItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_includeSubfoldersItemStateChanged

    private void allMatchingLinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allMatchingLinesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allMatchingLinesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox allMatchingFiles;
    private javax.swing.JCheckBox allMatchingLines;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox caseSensitive;
    private javax.swing.JButton close;
    private javax.swing.JComboBox fileFilter;
    private javax.swing.JButton find;
    private javax.swing.JComboBox folder;
    private javax.swing.JButton folderBrowse;
    private javax.swing.JComboBox folderFilter;
    private javax.swing.JButton help;
    private javax.swing.JCheckBox highlightSearch;
    private javax.swing.JCheckBox includeSubfolders;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox searchKey;
    private javax.swing.JCheckBox wholeWord;
    // End of variables declaration//GEN-END:variables
    /**
     * The container dialog window.
     */
    private JDialog containerWindow;

    public EditorContext getContext() {
        return EditorBase.getContext();
    }

    /**
     * Returns the data model for search key dropdown. It gets the list
     * of search keys from search data model.
     * @return The data model for search key dropdown.
     */
    public ComboBoxModel getSearchKeyListModel() {
        return new DefaultComboBoxModel(new Vector(model.getSearchKeys()));
    }

    /**
     *
     * @return
     */
    public ComboBoxModel getFolderListModel() {
        return new DefaultComboBoxModel(new Vector(model.getSearchKeys()));
    }

    /**
     *
     * @return
     */
    public ComboBoxModel getFileFilterListModel() {
        return new DefaultComboBoxModel(new Vector(model.getSearchKeys()));
    }

    /**
     * 
     * @return
     */
    public ComboBoxModel getFolderFilterListModel() {
        return new DefaultComboBoxModel(new Vector(model.getSearchKeys()));
    }

    /**
     * A key listener for 'search text' field. It is useful for incremental search.
     */
    protected class SearchTextKeyListener extends KeyAdapter {

        /**
         * Invoked when a key has been released.
         * @param e The key event.
         */
        @Override
        public void keyReleased(KeyEvent e) {
            model.setSearchKey((String) searchKey.getEditor().getItem());
            if (model.isIncrementalSearch()) {
                findEvent.execute(model);
            }
        }
    }
}
