/*
 * EditDocumentType.java
 * Created on 19 Oct, 2009, 3:55:42 PM
 *
 * Copyright (C) 2010 Mrityunjoy Saha
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package org.apex.base.settings.ui;

import javax.swing.JList;
import javax.swing.text.AbstractDocument;
import org.apex.base.data.AlphaNumericFilter;
import org.apex.base.data.DocumentType;
import org.apex.base.data.IDocumentType;
import org.apex.base.settings.DocumentTypesConfiguration;
import org.apex.base.settings.InvalidSettingsParameterException;
import org.apex.base.settings.SettingsMessageManager;
import org.apex.base.settings.ui.text.UIConfigurationUtility;
import org.apex.base.util.ConfigurationUtility;

/**
 * This is the view for editing custom document types.
 * @author mrityunjoy_saha
 * @version 1.0
 * @since Apex 1.2
 */
public class EditDocumentType extends DocumentTypeChangeSupport {

    /**
     * The index of selected document extension.
     */
    private int selectedDocumentTypeIndex;

    /**
     * Creates new form EditDocumentType.
     * @param docTypesConfig Document types configuration.
     * @param selectedDocumentType Selected document type.
     * @param docTypesList A list where document types are displayed.
     */
    public EditDocumentType(DocumentTypesConfiguration docTypesConfig,
            IDocumentType selectedDocumentType,
            JList docTypesList) {
        super(docTypesConfig, selectedDocumentType, docTypesList);
        this.selectedDocumentTypeIndex = docTypesList.getSelectedIndex();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        documentClass = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tokens = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        displayName = new javax.swing.JTextField();
        ((AbstractDocument)this.displayName.getDocument()).setDocumentFilter(new AlphaNumericFilter(15));
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        ok = new javax.swing.JButton();
        docType = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        defaultExtension = new javax.swing.JTextField();
        ((AbstractDocument)this.defaultExtension.getDocument()).setDocumentFilter(new AlphaNumericFilter(15));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/apex/base/settings/ui/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("EditDocumentType.jLabel1.text")); // NOI18N

        jLabel2.setText(bundle.getString("EditDocumentType.jLabel2.text")); // NOI18N

        documentClass.setText(getDocumentClass());
        documentClass.setToolTipText(bundle.getString("EditDocumentType.documentClass.toolTipText")); // NOI18N

        jLabel3.setText(bundle.getString("EditDocumentType.jLabel3.text")); // NOI18N

        tokens.setColumns(20);
        tokens.setRows(5);
        tokens.setText(getTokens());
        jScrollPane1.setViewportView(tokens);

        jLabel4.setText(bundle.getString("EditDocumentType.jLabel4.text")); // NOI18N

        displayName.setText(getDisplayName());

        jLabel5.setText(bundle.getString("EditDocumentType.jLabel5.text")); // NOI18N

        jLabel6.setText(bundle.getString("EditDocumentType.jLabel6.text")); // NOI18N

        cancel.setText(bundle.getString("EditDocumentType.cancel.text")); // NOI18N
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        ok.setText(bundle.getString("EditDocumentType.ok.text")); // NOI18N
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        docType.setText(getDocumentTypeName());

        jLabel7.setText(bundle.getString("EditDocumentType.jLabel7.text")); // NOI18N

        defaultExtension.setText(getDefaultExtension());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(displayName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(docType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel3)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(documentClass, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(defaultExtension, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ok)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(docType, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(defaultExtension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(documentClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(ok))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed

        String docDisplayName = this.displayName.getText();
        String docDefaultExtension = this.defaultExtension.getText();
        String docClass = this.documentClass.getText();
        String tokensList = this.tokens.getText();
        try {
            validateDisplayName(docDisplayName);
            validateDefaultExtension(docDefaultExtension);
            validateDocumentClass(docClass);
            validateTokens(tokensList);
            IDocumentType newDocType = new DocumentType(getDocumentTypeName(),
                    docDisplayName,
                    docDefaultExtension,
                    docClass,
                    ConfigurationUtility.getListFromString(tokensList, ","),
                    true);
            this.docTypesConfig.getDocumentTypes().set(
                    this.selectedDocumentTypeIndex, newDocType);
            this.docTypesList.setModel(UIConfigurationUtility.getListModel(this.docTypesConfig.
                    getDocumentTypes()));
            this.docTypesList.setSelectedIndex(this.selectedDocumentTypeIndex);
            closeWindow();
        } catch (InvalidSettingsParameterException ispe) {
            SettingsMessageManager.showErrorMessage(this, ispe.getErrorCode(),
                    ispe.getPlaceHolders());
            this.displayName.requestFocus();
        }
    }//GEN-LAST:event_okActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        closeWindow();
    }//GEN-LAST:event_cancelActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JTextField defaultExtension;
    private javax.swing.JTextField displayName;
    private javax.swing.JLabel docType;
    private javax.swing.JTextField documentClass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ok;
    private javax.swing.JTextArea tokens;
    // End of variables declaration//GEN-END:variables
}
