/*
 * GeneralSection.java
 * Created on 12 July, 2007, 12:50 AM 
 *
 * Copyright (C) 2008 Mrityunjoy Saha
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package org.apex.base.settings.ui;

import org.apex.base.data.AlphaNumericFilter;
import org.apex.base.settings.GeneralSectionConfiguration;
import org.apex.base.settings.ui.text.UIConfigurationDataModel;
import org.apex.base.settings.ui.text.UIConfigurationUtility;
import javax.swing.JSpinner.DefaultEditor;
import javax.swing.text.AbstractDocument;

/**
 * A form to update general attributes like 'View line numbers', 'caret color' etc.
 * @author Mrityunjoy Saha
 * @version 1.2
 * @since Apex 1.0
 */
public class GeneralSection extends javax.swing.JPanel implements
        UIConfigurationDataModel {

    /**
     * General configuration.
     */
    private GeneralSectionConfiguration generalSecConfig;

    /**
     * Creates new form {@code GeneralSection} using given general
     * configuration.
     * @param generalSecConfig General configuration.
     */
    public GeneralSection(
            GeneralSectionConfiguration generalSecConfig) {
        this.generalSecConfig = generalSecConfig;
        initComponents();
        applyConfiguration();
    }

    /**
     * Changes the enable state of fields within right margin block. When view right
     * margin option is selected remaining two buttons are enabled, otherwise disabled.
     * @param selected
     */
    private void enableRightMarginBlock(boolean selected) {
        this.rightMargin.setEnabled(selected);
        this.marginColorChooser.setEnabled(selected);
        this.sampleMarginColor.setEditable(selected);
        this.marginColorLabel.setEnabled(selected);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caretSection = new javax.swing.JPanel();
        caretColorTitle = new javax.swing.JLabel();
        caretColorChooser = new javax.swing.JButton();
        caretColorLabel = new javax.swing.JLabel();
        sampleCaretColor = new javax.swing.JTextField();
        formattingSection = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tabWidth = new javax.swing.JSpinner();
        rightmarginSection = new javax.swing.JPanel();
        caretColorLabel1 = new javax.swing.JLabel();
        viewRightMargin = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        caretColorTitle1 = new javax.swing.JLabel();
        sampleMarginColor = new javax.swing.JTextField();
        marginColorChooser = new javax.swing.JButton();
        marginColorLabel = new javax.swing.JLabel();
        rightMargin = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        viewStatusBar = new javax.swing.JCheckBox();
        viewDocumentSelector = new javax.swing.JCheckBox();
        defaultExtension = new javax.swing.JTextField();
        ((AbstractDocument)this.defaultExtension.getDocument()).setDocumentFilter(new AlphaNumericFilter(15));
        reuseConsole = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        maxRecentFilesCount = new javax.swing.JSpinner();

        caretSection.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cursor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 153))); // NOI18N

        caretColorTitle.setText("Cursor Color:");

        caretColorChooser.setText("Choose");
        caretColorChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caretColorChooserHandler(evt);
            }
        });

        caretColorLabel.setText(" ");

        sampleCaretColor.setEnabled(false);
        sampleCaretColor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                sampleCaretColorPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout caretSectionLayout = new javax.swing.GroupLayout(caretSection);
        caretSection.setLayout(caretSectionLayout);
        caretSectionLayout.setHorizontalGroup(
            caretSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caretSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(caretColorTitle)
                .addGap(18, 18, 18)
                .addComponent(sampleCaretColor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(caretColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(caretColorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        caretSectionLayout.setVerticalGroup(
            caretSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caretSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(sampleCaretColor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(caretColorChooser)
                .addComponent(caretColorLabel)
                .addComponent(caretColorTitle))
        );

        formattingSection.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formatting", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 153))); // NOI18N

        jLabel1.setText("Tab Width:");

        jLabel4.setText("spaces");

        tabWidth.setModel(new javax.swing.SpinnerNumberModel(2, 2, 12, 1));
        tabWidth.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabWidthStateChanged(evt);
            }
        });

        javax.swing.GroupLayout formattingSectionLayout = new javax.swing.GroupLayout(formattingSection);
        formattingSection.setLayout(formattingSectionLayout);
        formattingSectionLayout.setHorizontalGroup(
            formattingSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formattingSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tabWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        formattingSectionLayout.setVerticalGroup(
            formattingSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formattingSectionLayout.createSequentialGroup()
                .addGroup(formattingSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tabWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addContainerGap(6, Short.MAX_VALUE))
        );

        if (tabWidth.getEditor() instanceof DefaultEditor) {
            ((DefaultEditor) tabWidth.getEditor()).getTextField().setEditable(false);
        }

        rightmarginSection.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Right Margin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 153))); // NOI18N

        caretColorLabel1.setText(" ");

        viewRightMargin.setText("View Right Margin");
        viewRightMargin.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                viewRightMarginItemStateChanged(evt);
            }
        });

        jLabel2.setText("Right Margin:");

        caretColorTitle1.setText("Margin Color:");

        sampleMarginColor.setEnabled(false);
        sampleMarginColor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                sampleMarginColorPropertyChange(evt);
            }
        });

        marginColorChooser.setText("Choose");
        marginColorChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marginColorChooserHandler(evt);
            }
        });

        marginColorLabel.setText(" ");

        rightMargin.setModel(new javax.swing.SpinnerNumberModel(80, 10, 150, 1));
        rightMargin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rightMarginStateChanged(evt);
            }
        });

        javax.swing.GroupLayout rightmarginSectionLayout = new javax.swing.GroupLayout(rightmarginSection);
        rightmarginSection.setLayout(rightmarginSectionLayout);
        rightmarginSectionLayout.setHorizontalGroup(
            rightmarginSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightmarginSectionLayout.createSequentialGroup()
                .addGroup(rightmarginSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightmarginSectionLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(caretColorLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rightmarginSectionLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(rightmarginSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rightmarginSectionLayout.createSequentialGroup()
                                .addComponent(caretColorTitle1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sampleMarginColor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(marginColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(marginColorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rightmarginSectionLayout.createSequentialGroup()
                                .addComponent(viewRightMargin)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rightMargin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rightmarginSectionLayout.setVerticalGroup(
            rightmarginSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightmarginSectionLayout.createSequentialGroup()
                .addGroup(rightmarginSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewRightMargin)
                    .addComponent(jLabel2)
                    .addComponent(rightMargin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rightmarginSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caretColorTitle1)
                    .addComponent(marginColorChooser)
                    .addComponent(sampleMarginColor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marginColorLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(caretColorLabel1)
                .addGap(41, 41, 41))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Defaults", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 153))); // NOI18N

        jLabel5.setText("Default Document Extension:");

        viewStatusBar.setText("View Status Bar");
        viewStatusBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStatusBarActionPerformed(evt);
            }
        });

        viewDocumentSelector.setText("View Document Selector");
        viewDocumentSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDocumentSelectorActionPerformed(evt);
            }
        });

        defaultExtension.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                defaultExtensionKeyReleased(evt);
            }
        });

        reuseConsole.setText("Reuse console");
        reuseConsole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reuseConsoleActionPerformed(evt);
            }
        });

        jLabel3.setText("Maximum Recent Files:");

        maxRecentFilesCount.setModel(new javax.swing.SpinnerNumberModel(5, 1, 15, 1));
        maxRecentFilesCount.setOpaque(false);
        maxRecentFilesCount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                maxRecentFilesCountStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewDocumentSelector)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(viewStatusBar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reuseConsole)
                            .addComponent(maxRecentFilesCount, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(defaultExtension, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {reuseConsole, viewStatusBar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(defaultExtension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(maxRecentFilesCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                .addComponent(viewDocumentSelector)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewStatusBar)
                    .addComponent(reuseConsole)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {reuseConsole, viewStatusBar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(caretSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formattingSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rightmarginSection, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {caretSection, jPanel1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caretSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formattingSection, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightmarginSection, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void caretColorChooserHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caretColorChooserHandler
        UIConfigurationUtility.colorChooserHandler(this.caretColorLabel,
                this.sampleCaretColor);
    }//GEN-LAST:event_caretColorChooserHandler

    private void sampleCaretColorPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_sampleCaretColorPropertyChange
        this.generalSecConfig.setCaretColor(sampleCaretColor.getBackground());
    }//GEN-LAST:event_sampleCaretColorPropertyChange

private void defaultExtensionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_defaultExtensionKeyReleased
    this.generalSecConfig.setDefaultExtension(this.defaultExtension.getText().
            trim());
}//GEN-LAST:event_defaultExtensionKeyReleased

private void tabWidthStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabWidthStateChanged
    this.generalSecConfig.setTabSize((Integer) this.tabWidth.getValue());
}//GEN-LAST:event_tabWidthStateChanged

private void sampleMarginColorPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_sampleMarginColorPropertyChange
    this.generalSecConfig.setRightMarginColor(sampleMarginColor.getBackground());
}//GEN-LAST:event_sampleMarginColorPropertyChange

private void marginColorChooserHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marginColorChooserHandler
    UIConfigurationUtility.colorChooserHandler(this.marginColorLabel,
            this.sampleMarginColor);
}//GEN-LAST:event_marginColorChooserHandler

private void viewRightMarginItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_viewRightMarginItemStateChanged
    this.generalSecConfig.setViewRightMargin(viewRightMargin.isSelected());
    enableRightMarginBlock(viewRightMargin.isSelected());
}//GEN-LAST:event_viewRightMarginItemStateChanged

private void rightMarginStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rightMarginStateChanged
    this.generalSecConfig.setRightMargin((Integer) this.rightMargin.getValue());
}//GEN-LAST:event_rightMarginStateChanged

private void viewDocumentSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDocumentSelectorActionPerformed
    this.generalSecConfig.setViewDocumentSelector(viewDocumentSelector.
            isSelected());
}//GEN-LAST:event_viewDocumentSelectorActionPerformed

private void viewStatusBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStatusBarActionPerformed
    this.generalSecConfig.setViewStatusBar(viewStatusBar.isSelected());
}//GEN-LAST:event_viewStatusBarActionPerformed

private void maxRecentFilesCountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_maxRecentFilesCountStateChanged
    this.generalSecConfig.setMaxRecentFilesCount((Integer) this.maxRecentFilesCount.
            getValue());
}//GEN-LAST:event_maxRecentFilesCountStateChanged

private void reuseConsoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reuseConsoleActionPerformed
    this.generalSecConfig.setReuseConsole(reuseConsole.isSelected());
}//GEN-LAST:event_reuseConsoleActionPerformed

    public void applyConfiguration() {
        // Default Document Extension        
        this.defaultExtension.setText(generalSecConfig.getDefaultExtension());
        // Document selector
        viewDocumentSelector.setSelected(
                generalSecConfig.isViewDocumentSelector());
        // Status bar
        viewStatusBar.setSelected(generalSecConfig.isViewStatusBar());
        // Caret Color        
        UIConfigurationUtility.showColor(generalSecConfig.getCaretColor(),
                caretColorLabel,
                sampleCaretColor);
        // Caret Width        
        //this.caretWidth.setValue(generalSecConfig.getCaretWidth());
        // View Line Number
        // @TODO Once View line number menu is activated again uncomment following line
        //viewLineNumber.setSelected(generalSecConfig.isViewLineNumber());
        // Tab Size
        tabWidth.setValue(generalSecConfig.getTabSize());
        // Indentation Size
        //indentationSize.setValue(generalSecConfig.getIndentationSize());
        viewRightMargin.setSelected(generalSecConfig.isViewRightMargin());
        rightMargin.setValue(generalSecConfig.getRightMargin());
        UIConfigurationUtility.showColor(generalSecConfig.getRightMarginColor(),
                marginColorLabel,
                sampleMarginColor);
        viewRightMargin.setSelected(generalSecConfig.isViewRightMargin());
        maxRecentFilesCount.setValue(generalSecConfig.getMaxRecentFilesCount());
        reuseConsole.setSelected(generalSecConfig.isReuseConsole());
        enableRightMarginBlock(generalSecConfig.isViewRightMargin());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton caretColorChooser;
    private javax.swing.JLabel caretColorLabel;
    private javax.swing.JLabel caretColorLabel1;
    private javax.swing.JLabel caretColorTitle;
    private javax.swing.JLabel caretColorTitle1;
    private javax.swing.JPanel caretSection;
    private javax.swing.JTextField defaultExtension;
    private javax.swing.JPanel formattingSection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton marginColorChooser;
    private javax.swing.JLabel marginColorLabel;
    private javax.swing.JSpinner maxRecentFilesCount;
    private javax.swing.JCheckBox reuseConsole;
    private javax.swing.JSpinner rightMargin;
    private javax.swing.JPanel rightmarginSection;
    private javax.swing.JTextField sampleCaretColor;
    private javax.swing.JTextField sampleMarginColor;
    private javax.swing.JSpinner tabWidth;
    private javax.swing.JCheckBox viewDocumentSelector;
    private javax.swing.JCheckBox viewRightMargin;
    private javax.swing.JCheckBox viewStatusBar;
    // End of variables declaration//GEN-END:variables
}
